steps:
  - name: ':docker: Build Docker image for tests'
    command: 'auto/build-image-for-test'
    agents:
      queue: muppets:build

  - wait

  - name: ':elixir: Run unit tests'
    command: 'auto/tests/specs'
    agents:
      queue: flatmates:deploy

  - name: ':elixir: Check code format'
    command: 'auto/tests/format'
    agents:
      queue: flatmates:deploy
